export const CURRENT_FORCAST_SET = 'CURRENT_FORCAST_SET';
export const SELECTED_CITY_SET = 'SELECTED_CITY_SET';
export const SELECTED_DATE_SET = 'SELECTED_DATE_SET';
export const WEATHER_DATA_ATTEMPT = 'WEATHER_DATA_ATTEMPT';
export const WEATHER_DATA_FAILURE = 'WEATHER_DATA_FAILURE';
export const WEATHER_DATA_SET = 'WEATHER_DATA_SET';
