export const RESULTS_NOT_FOUND = 'RESULTS_NOT_FOUND';
export const CURRENT_FORCAST_SET = 'CURRENT_FORCAST_SET';
export const SELECTED_CITY_SET = 'SELECTED_CITY_SET';
export const SELECTED_DATE_SET = 'SELECTED_DATE_SET';
export const WEATHER_DATA_FETCH_ATTEMPT = 'WEATHER_DATA_FETCH_ATTEMPT';
export const WEATHER_DATA_FETCH_FAILURE = 'WEATHER_DATA_FETCH_FAILURE';
export const WEATHER_DATA_SET = 'WEATHER_DATA_SET';
